// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_fJ3ocg15u8zTLQqCEW6Hq2UFIYUARr8',
    appId: '1:572045999446:web:44c85a72d6558c6537eaf7',
    messagingSenderId: '572045999446',
    projectId: 'weather-app-bc122',
    authDomain: 'weather-app-bc122.firebaseapp.com',
    storageBucket: 'weather-app-bc122.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxT1h9bu8c3FA7W4bVhuVN1karg9FxE9k',
    appId: '1:572045999446:android:23d1f4ca226dc44837eaf7',
    messagingSenderId: '572045999446',
    projectId: 'weather-app-bc122',
    storageBucket: 'weather-app-bc122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlA9-2RQsTaNNEnH-RwHXNSrpMC7yp5S8',
    appId: '1:572045999446:ios:730ff41f3e96da6337eaf7',
    messagingSenderId: '572045999446',
    projectId: 'weather-app-bc122',
    storageBucket: 'weather-app-bc122.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlA9-2RQsTaNNEnH-RwHXNSrpMC7yp5S8',
    appId: '1:572045999446:ios:730ff41f3e96da6337eaf7',
    messagingSenderId: '572045999446',
    projectId: 'weather-app-bc122',
    storageBucket: 'weather-app-bc122.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_fJ3ocg15u8zTLQqCEW6Hq2UFIYUARr8',
    appId: '1:572045999446:web:2eb19dea679b347137eaf7',
    messagingSenderId: '572045999446',
    projectId: 'weather-app-bc122',
    authDomain: 'weather-app-bc122.firebaseapp.com',
    storageBucket: 'weather-app-bc122.firebasestorage.app',
  );
}
